# Generated by Django 4.1 on 2022-12-21 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="journeyDetails",
            fields=[
                (
                    "id",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=100)),
                ("hall", models.CharField(max_length=100)),
                ("date", models.DateField(max_length=100)),
                ("time", models.TimeField(max_length=100)),
                ("Blocation", models.CharField(max_length=100)),
                ("Dlocation", models.CharField(max_length=100)),
            ],
            options={"db_table": "myapp_journeydetails", "managed": False,},
        ),
    ]
