# Generated by Django 4.1 on 2023-01-05 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="journeydetails",
            name="username",
            field=models.CharField(max_length=150),
        ),
    ]
