# Generated by Django 4.1 on 2022-12-21 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(name="journeydetails", table="details",),
    ]
