# Generated by Django 4.1 on 2022-12-27 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0002_alter_journeydetails_table"),
    ]

    operations = [
        migrations.CreateModel(
            name="Loggedin",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("loggedin", models.CharField(max_length=100)),
            ],
            options={"db_table": "login", "managed": False,},
        ),
    ]
