# Generated by Django 4.1 on 2022-12-30 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0003_loggedin"),
    ]

    operations = [
        migrations.CreateModel(
            name="contactinfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("email", models.EmailField(max_length=50)),
                ("subject", models.CharField(max_length=100)),
                ("message", models.CharField(max_length=200)),
            ],
            options={"db_table": "wantstocontact", "managed": False,},
        ),
    ]
